"""seam_index.py - one line per section of docs/SEAM.md (its heading, trimmed), so "has this been tried?" is a grep.
    uv run python scripts/seam_index.py > docs/SEAM_INDEX.md"""
import re
lines = open("docs/SEAM.md").read().split("\n")
print("# SEAM index (generated by scripts/seam_index.py; do not edit)\n")
for i, l in enumerate(lines, 1):
    if l.startswith("## "): print(f"- L{i}: {l[3:].strip()[:160]}")
